
// This file has been generated by the GUI designer. Do not modify.
namespace LocalLexicon
{
	public partial class WordWidget
	{
		private global::Gtk.Table table1;
		
		private global::Gtk.Entry glossEntry;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView definitionText;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Entry lexEntry;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LocalLexicon.WordWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LocalLexicon.WordWidget";
			// Container child LocalLexicon.WordWidget.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.glossEntry = new global::Gtk.Entry ();
			this.glossEntry.CanFocus = true;
			this.glossEntry.Name = "glossEntry";
			this.glossEntry.IsEditable = true;
			this.glossEntry.InvisibleChar = '•';
			this.table1.Add (this.glossEntry);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.glossEntry]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.definitionText = new global::Gtk.TextView ();
			this.definitionText.CanFocus = true;
			this.definitionText.Name = "definitionText";
			this.GtkScrolledWindow.Add (this.definitionText);
			this.table1.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.GtkScrolledWindow]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("_Lexeme");
			this.label1.UseUnderline = true;
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("_Gloss");
			this.label2.UseUnderline = true;
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("_Definition");
			this.label3.UseUnderline = true;
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(7));
			// Container child table1.Gtk.Table+TableChild
			this.lexEntry = new global::Gtk.Entry ();
			this.lexEntry.CanFocus = true;
			this.lexEntry.Name = "lexEntry";
			this.lexEntry.IsEditable = true;
			this.lexEntry.InvisibleChar = '•';
			this.table1.Add (this.lexEntry);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.lexEntry]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.label1.MnemonicWidget = this.lexEntry;
			this.label2.MnemonicWidget = this.glossEntry;
			this.Hide ();
			this.lexEntry.Changed += new global::System.EventHandler (this.OnLexEntryChanged);
			this.lexEntry.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnLexEntryFocusOutEvent);
			this.lexEntry.FocusInEvent += new global::Gtk.FocusInEventHandler (this.OnLexEntryFocusInEvent);
			this.definitionText.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnDefinitionTextFocusOutEvent);
			this.glossEntry.Changed += new global::System.EventHandler (this.OnGlossEntryChanged);
		}
	}
}
