
// This file has been generated by the GUI designer. Do not modify.
namespace LocalLexicon
{
	public partial class SearchWidget
	{
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Entry searchTerm;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LocalLexicon.SearchWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LocalLexicon.SearchWidget";
			// Container child LocalLexicon.SearchWidget.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Search for:");
			this.hbox2.Add (this.label4);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label4]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.searchTerm = new global::Gtk.Entry ();
			this.searchTerm.CanFocus = true;
			this.searchTerm.Name = "searchTerm";
			this.searchTerm.IsEditable = true;
			this.searchTerm.InvisibleChar = '•';
			this.hbox2.Add (this.searchTerm);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.searchTerm]));
			w2.Position = 1;
			this.Add (this.hbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
