
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action newAction;
	
	private global::Gtk.Action openAction;
	
	private global::Gtk.Action saveAction;
	
	private global::Gtk.Action NewWordAction;
	
	private global::Gtk.Action DeleteWordAction;
	
	private global::Gtk.Action LanguagePropertiesAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::LocalLexicon.SearchWidget search;
	
	private global::Gtk.HPaned hpaned1;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TreeView wordList;
	
	private global::LocalLexicon.WordWidget currentWord;
	
	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.newAction = new global::Gtk.Action ("newAction", global::Mono.Unix.Catalog.GetString ("New"), null, "gtk-new");
		this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New");
		w1.Add (this.newAction, null);
		this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("Open"), null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.openAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, "gtk-save");
		this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.saveAction, null);
		this.NewWordAction = new global::Gtk.Action ("NewWordAction", global::Mono.Unix.Catalog.GetString ("New word"), null, null);
		this.NewWordAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New word");
		w1.Add (this.NewWordAction, null);
		this.DeleteWordAction = new global::Gtk.Action ("DeleteWordAction", global::Mono.Unix.Catalog.GetString ("Delete word"), null, null);
		this.DeleteWordAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Delete word");
		w1.Add (this.DeleteWordAction, null);
		this.LanguagePropertiesAction = new global::Gtk.Action ("LanguagePropertiesAction", global::Mono.Unix.Catalog.GetString ("Language properties"), null, null);
		this.LanguagePropertiesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Language properties");
		w1.Add (this.LanguagePropertiesAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='newAction' action='newAction'/><menuitem name='openAction' action='openAction'/><menuitem name='saveAction' action='saveAction'/><menuitem name='NewWordAction' action='NewWordAction'/><menuitem name='DeleteWordAction' action='DeleteWordAction'/><menuitem name='LanguagePropertiesAction' action='LanguagePropertiesAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.search = new global::LocalLexicon.SearchWidget ();
		this.search.Events = ((global::Gdk.EventMask)(256));
		this.search.Name = "search";
		this.vbox1.Add (this.search);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.search]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 296;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.wordList = new global::Gtk.TreeView ();
		this.wordList.CanFocus = true;
		this.wordList.Name = "wordList";
		this.GtkScrolledWindow1.Add (this.wordList);
		this.hpaned1.Add (this.GtkScrolledWindow1);
		global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.GtkScrolledWindow1]));
		w5.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.currentWord = new global::LocalLexicon.WordWidget ();
		this.currentWord.Events = ((global::Gdk.EventMask)(256));
		this.currentWord.Name = "currentWord";
		this.hpaned1.Add (this.currentWord);
		this.vbox1.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
		w7.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w8.Position = 3;
		w8.Expand = false;
		w8.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 975;
		this.DefaultHeight = 738;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.newAction.Activated += new global::System.EventHandler (this.OnNewActionActivated);
		this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.saveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
		this.NewWordAction.Activated += new global::System.EventHandler (this.OnNewWordActionActivated);
		this.DeleteWordAction.Activated += new global::System.EventHandler (this.OnDeleteWordActionActivated);
		this.LanguagePropertiesAction.Activated += new global::System.EventHandler (this.OnLanguagePropertiesActionActivated);
		this.wordList.CursorChanged += new global::System.EventHandler (this.OnWordListCursorChanged);
	}
}
